### ISSUE TITLE
windows下编译java wrapper报错

### ISSUE THREAD

**Issue by happyycm** [beyonderyue/gmssl-java#1]
您好，首先感谢您修改的GmSSL版本。
我这边linux下编译java wrapper可以通过（还未测试使用）
但是在windows下编译java wrapper会报一下错误

`GmSSL.obj : error LNK2019: 无法解析的外部符号 ec_key_simple_generate_public_key，该符号在函数 Java_com_yzz_gmssl_GmSSL_calculateSharedKey 中被引用
GmSSL.obj : error LNK2019: 无法解析的外部符号 SM2_KAP_prepare_no_rand，该符号在函数 Java_com_yzz_gmssl_GmSSL_calculateSharedKey 中被引用
gmssljni.dll : fatal error LNK1120: 2 个无法解析的外部命令
NMAKE : fatal error U1077: “D:\VisualStudio\VC\Tools\MSVC\14.25.28610\bin\HostX64\x64\link.EXE”: 返回代码“0x460”`

查看C的代码，是比官方的多使用了ec_key_simple_generate_public_key和SM2_KAP_prepare_no_rand两个函数。请问问改怎么修改才可以在windows下也编译成功呢？

**Comment by beyonderyue** [comment]
抱歉，不支持windows，没有编译过windows下的c库

**Comment by happyycm** [comment]
> 抱歉，不支持windows，没有编译过windows下的c库

好的，谢谢。
